// Code generated by Icestudio 0.12
// Sun, 15 Feb 2026 21:29:35 GMT

`default_nettype none

//---- Top entity
module tt_um_vga_example (
    // 8 Input‑Pins
    input  wire [7:0] ui_in,
    

    // 8 Output‑Pins
    output wire [7:0] uo_out,

    // 8 bidirektionale Pins
    input  wire [7:0] uio_in,
    output wire [7:0] uio_out,
    output wire [7:0] uio_oe,

    // Steuer‑Signale vom Multiplexer
    input  wire ena,   // wird 1, wenn dein Design „dran“ ist
    input  wire clk,   // globaler Clock
    input  wire rst_n  // Reset, aktiv low
);

    // unbenanntes internes Top (dein altes main)
    wire [7:0] seg;

    tt_core main_inst (
        .vclk    (clk),
        .v398a87 (seg)
            // Dummy connects für CHECK
    );

    assign uo_out = seg;      // z.B. 7‑Segment + Select rausführen
    assign uio_out = 8'b0;
    assign uio_oe  = 8'b0;    // alles als Eingang lassen

endmodule


module tt_core #(
  parameter v38ccab = 10,
  parameter vbb681f = 500
) (
  input        vclk,
  output [7:0] v398a87
);
  localparam p1 = vbb681f;
  localparam p3 = v38ccab;
    wire [7:0] w0;
  wire       w2;
  wire       w4;
  wire       w5;
  wire       w6;

  assign v398a87 = w0;
  assign w5      = vclk;
  assign w6      = vclk;
  assign w6      = w5;

  v4aa649 #(
    .v93035e(p1)
  ) v5d193e (
    .v4642b6(w2),
    .v6dda25(w5)
  );

  v4aa649 #(
    .v93035e(p3)
  ) v145d26 (
    .v4642b6(w4),
    .v6dda25(w6)
  );

  main_v3d4960 v3d4960 (
    .OUT(w0),
    .clock(w2),
    .disp_sel(w4)
  );
endmodule

//---------------------------------------------------
//-- Led on
//---------------------------------------------------
//---- Top entity
module v4aa649 #(
  parameter v5c678e = 12_000_000,
  parameter v93035e = 1
) (
  input  v6dda25,
  output v4642b6
);
  localparam p4 = v5c678e;
  localparam p5 = v93035e;
  wire        w0;
    wire [31:0] w1;
  wire [31:0] w2;
  wire        w3;
  wire        w6;
  wire        w7;
  wire        w8;

  assign w6       = v6dda25;
  assign w7       = v6dda25;
  assign v4642b6  = w8;
  assign w7       = w6;

  vd30ca9 vd4bd91 (
    .v9fb85f(w3)
  );

  vaaf5c4 vf7ffa3 (
    .v51eedb(w1),
    .v4f6beb(w2),
    .v712289(w3)
  );

  v7f4a3c #(
    .vb310e3(p4),
    .v7e2e6d(p5)
  ) v03b2dc (
    .v88811d(w2)
  );

  v9cd840 v0c12e7 (
    .v4642b6(w0),
    .vdd8a3d(w1),
    .v6dda25(w6)
  );

  vb7f713 v0e0931 (
    .vb5e8cd(w0),
    .v6dda25(w7),
    .v4642b6(w8)
  );
endmodule

//---------------------------------------------------
//-- Simplified-Heart-ms-32bits
//---------------------------------------------------
//---- Top entity
module vd30ca9 (
  output v9fb85f
);
  wire w0;
  assign v9fb85f = w0;

  vd30ca9_vb2eccd vb2eccd (
    .q(w0)
  );
endmodule

//---------------------------------------------------
//-- bit-0
//---------------------------------------------------
module vd30ca9_vb2eccd (
  output q
);
  //-- Constant bit-0
  assign q = 1'b0;
endmodule

//---- Top entity
module vaaf5c4 (
  input        v712289,
  input  [31:0] v4f6beb,
  output [31:0] v51eedb,
  output       v7e4f0f
);
  wire [0:31] w0;
  wire        w1;
  wire        w2;
  wire [0:30] w3;
  wire [0:31] w4;

  assign w0      = v4f6beb;
  assign v7e4f0f = w1;
  assign w2      = v712289;
  assign v51eedb = w4;

  vecd30a vd4273f (
    .ve841af(w0),
    .v8d1a42(w1),
    .v11ef80(w3)
  );

  v51b3c0 v9b7810 (
    .v411a12(w2),
    .vd40455(w3),
    .v7d0a31(w4)
  );
endmodule

//---------------------------------------------------
//-- SR1-32bits
//---------------------------------------------------
//---- Top entity
module vecd30a (
  input  [31:0] ve841af,
  output [30:0] v11ef80,
  output        v8d1a42
);
  wire [0:31] w0;
  wire        w1;
  wire [0:30] w2;

  assign w0      = ve841af;
  assign v8d1a42 = w1;
  assign v11ef80 = w2;

  vecd30a_v9a2a06 v9a2a06 (
    .i(w0),
    .o0(w1),
    .o1(w2)
  );
endmodule

//---------------------------------------------------
//-- Bus32-Split-31-1
//---------------------------------------------------
module vecd30a_v9a2a06 (
  input  [31:0] i,
  output [30:0] o1,
  output        o0
);
  assign o1 = i[31:1];
  assign o0 = i[0];
endmodule

//---- Top entity
module v51b3c0 (
  input        v411a12,
  input  [30:0] vd40455,
  output [31:0] v7d0a31
);
  wire [0:31] w0;
  wire [0:30] w1;
  wire        w2;

  assign v7d0a31 = w0;
  assign w1      = vd40455;
  assign w2      = v411a12;

  v51b3c0_v9a2a06 v9a2a06 (
    .o(w0),
    .i0(w1),
    .i1(w2)
  );
endmodule

//---------------------------------------------------
//-- Bus32-Join-1-31
//---------------------------------------------------
module v51b3c0_v9a2a06 (
  input        i1,
  input  [30:0] i0,
  output [31:0] o
);
  assign o = {i1, i0};
endmodule

//---- Top entity
module v7f4a3c #(
  parameter vb310e3 = 12000000,
  parameter v7e2e6d = 1
) (
  output [31:0] v88811d
);
  localparam p0 = vb310e3;
  localparam p2 = v7e2e6d;
  wire [0:31] w1;

  assign v88811d = w1;

  v7f4a3c_vb4f23b #(
    .F(p0),
    .MS(p2)
  ) vb4f23b (
    .n(w1)
  );
endmodule

//---------------------------------------------------
//-- Unit-ms-32bits
//---------------------------------------------------
module v7f4a3c_vb4f23b #(
  parameter F  = 0,
  parameter MS = 0
) (
  output [31:0] n
);
  localparam Cycles = $ceil(1.0e-3 * F * MS);

  assign n = Cycles;
endmodule

//---- Top entity
module v9cd840 (
  input        v6dda25,
  input  [31:0] vdd8a3d,
  output       v298468,
output [31:0] vdb018a,
  output       v4642b6
);
  wire        w0;
  wire        w1;
  wire        w2;
  wire        w3;
  wire        w4;
    
  wire [0:31] w6;
  wire        w7;
  wire        w8;

  assign w2       = v6dda25;
  assign w3       = v6dda25;
  assign v298468  = w4;

  assign w6       = vdd8a3d;
  assign v4642b6  = w7;
  assign w3       = w2;
  assign w8       = w7;

    assign v298468 = 1'b0;
assign vdb018a = 32'b0;
   // assign v369b88 = 32'b0; 

  v873425 v5ca286 (
    .vcbab45(w0),
    .v0e28cb(w1),
    .v3ca442(w8)
  );

  ve1fb38 vd76610 (
    .vd6d696(w0),
    .v251484(w2),
  //  .v4642b6(w4),
    //.v369b88(w5),
    .v16d4c6(w6),
    .ve485b0(w7)
  );

  v12181a v2eb2f6 (
    .v4642b6(w1),
    .vd6bebe(w3)
  );
endmodule

//---------------------------------------------------
//-- Heart-sys-zero-32bits
//---------------------------------------------------
//---- Top entity
module v873425 (
  input  v0e28cb,
  input  v3ca442,
  output vcbab45
);
  wire w0;
  wire w1;
  wire w2;

  assign w0      = v0e28cb;
  assign w1      = v3ca442;
  assign vcbab45 = w2;

  v873425_vf4938a vf4938a (
    .a(w0),
    .b(w1),
    .c(w2)
  );
endmodule

//---------------------------------------------------
//-- OR2
//---------------------------------------------------
module v873425_vf4938a (
  input  a,
  input  b,
  output c
);
  assign c = a | b;
endmodule

//---- Top entity
module ve1fb38 (
  input        v251484,
  input  [31:0] v16d4c6,
  input        vd6d696,
  output       v4642b6,
 // output [31:0] v369b88,
  output       ve485b0
);
  wire        w0;
  wire        w1;
  wire        w2;
  wire        w3;
  wire        w4;
  wire [0:31] w5;
  wire        w6;
  wire        w7;
  wire        w8;
  wire [0:31] w9;

  assign v4642b6 = w0;
  assign w2      = v251484;
  assign w3      = v251484;
  assign w4      = vd6d696;
  assign w5      = v16d4c6;
  assign ve485b0 = w8;
 // assign v369b88 =  32'b0;
  assign w1      = w0;
  assign w3      = w2;
  assign w7      = w6;
  assign w8      = w6;
  assign w8      = w7;

  vee22ae v0c70e9 (
    .v3dc29f(w1),
    .v6dda25(w3),
    .vd6b9df(w5),
    .vd1077b(w6),
    .vafbfaf(w7),
    .vd8c74e(w9)
  );

  vef2764 v6c1af0 (
    .v4642b6(w0),
    .v6dda25(w2),
    .v27dec4(w4),
    .v92a149(w6)
  );
endmodule

//---------------------------------------------------
//-- Sys-Delay-xN-32bits
//---------------------------------------------------
//---- Top entity
module vee22ae #(
  parameter vc0bbb5 = 0
) (
  input        v6dda25,
  input        vafbfaf,
  input  [31:0] vd6b9df,
  input        v3dc29f,
  output [31:0] vd8c74e,
  output       vd1077b
);
  localparam p3 = vc0bbb5;
  wire        w0;
  wire        w1;
  wire [0:31] w2;
  wire [0:31] w4;
  wire        w5;
  wire [0:31] w6;
  wire [0:31] w7;
  wire        w8;
  wire        w9;
  wire        w10;
  wire [0:31] w11;
  wire        w12;
  wire        w13;

  assign w5       = v6dda25;
  assign vd8c74e  = w6;
  assign w8       = vafbfaf;
  assign vd1077b  = w9;
  assign w11      = vd6b9df;
  assign w12      = v3dc29f;
  assign w13      = v3dc29f;
  assign w4       = w2;
  assign w7       = w6;
  assign w10      = w9;
  assign w13      = w12;

  vba518e v3611b7 (
    .vcbab45(w1),
    .v3ca442(w10),
    .v0e28cb(w12)
  );

  v873425 ve0ac7d (
    .vcbab45(w0),
    .v3ca442(w1),
    .v0e28cb(w8)
  );

  v0906c2 v9573bf (
    .v9d71f2(w2),
    .v95222c(w7)
  );

  va63735 va6a503 (
    .v1069e2(w4),
    .v4642b6(w9),
    .vd448df(w11)
  );

  vd5bdd7 #(
    .v4800df(p3)
  ) v49149b (
    .va5013b(w0),
    .v9406e4(w2),
    .v6dda25(w5),
    .v4db459(w6),
    .v23125b(w13)
  );
endmodule

//---------------------------------------------------
//-- Counter-M-rst-x32
//---------------------------------------------------
//---- Top entity
module vba518e (
  input  v0e28cb,
  input  v3ca442,
  output vcbab45
);
  wire w0;
  wire w1;
  wire w2;

  assign w0      = v0e28cb;
  assign w1      = v3ca442;
  assign vcbab45 = w2;

  vba518e_vf4938a vf4938a (
    .a(w0),
    .b(w1),
    .c(w2)
  );
endmodule

//---------------------------------------------------
//-- AND2
//---------------------------------------------------
module vba518e_vf4938a (
  input  a,
  input  b,
  output c
);
  assign c = a & b;
endmodule

//---- Top entity
module v0906c2 #(
  parameter v6c5139 = 1
) (
  input  [31:0] v95222c,
  output        v4642b6,
  output [31:0] v9d71f2
);
  localparam p1 = v6c5139;
  wire        w0;
  wire [0:31] w2;
  wire [0:31] w3;

  assign v4642b6 = w0;
  assign w2      = v95222c;
  assign v9d71f2 = w3;

  v3c5f22 #(
    .vd73390(p1)
  ) v3ec2b4 (
    .v4642b6(w0),
    .v56e20b(w2),
    .vc89e4a(w3)
  );
endmodule

//---------------------------------------------------
//-- Inc1-32bits
//---------------------------------------------------
//---- Top entity
module v3c5f22 #(
  parameter vd73390 = 0
) (
  input  [31:0] v56e20b,
  output        v4642b6,
  output [31:0] vc89e4a
);
  localparam p1 = vd73390;
  wire        w0;
  wire [0:31] w2;
  wire [0:31] w3;
  wire [0:31] w4;

  assign v4642b6 = w0;
  assign w3      = v56e20b;
  assign vc89e4a = w4;

  v959751 #(
    .vc5c8ea(p1)
  ) v389b9e (
    .vbc97e4(w2)
  );

  vf25742 v14cd53 (
    .v4642b6(w0),
    .v7bf4f3(w2),
    .vc67cc0(w3),
    .vc16efd(w4)
  );
endmodule

//---------------------------------------------------
//-- AdderK-32bits
//---------------------------------------------------
//---- Top entity
module v959751 #(
  parameter vc5c8ea = 0
) (
  output [31:0] vbc97e4
);
  localparam p0 = vc5c8ea;
  wire [0:31] w1;

  assign vbc97e4 = w1;

  v959751_v465065 #(
    .VALUE(p0)
  ) v465065 (
    .k(w1)
  );
endmodule

//---------------------------------------------------
//-- 32-bits-gen-constant
//---------------------------------------------------
module v959751_v465065 #(
  parameter VALUE = 0
) (
  output [31:0] k
);
  assign k = VALUE;
endmodule

//---- Top entity
module vf25742 (
  input  [31:0] v7bf4f3,
  input  [31:0] vc67cc0,
  output        v4642b6,
  output [31:0] vc16efd
);
  wire        w0;
  wire [0:7]  w1;
  wire [0:7]  w2;
  wire        w3;
  wire [0:15] w4;
  wire [0:7]  w5;
  wire        w6;
  wire [0:23] w7;
  wire        w8;
  wire [0:31] w9;
  wire [0:23] w10;
  wire [0:15] w11;
  wire [0:31] w12;
  wire [0:23] w13;
  wire [0:15] w14;
  wire [0:7]  w15;
  wire [0:31] w16;
  wire [0:7]  w17;
  wire [0:7]  w18;
  wire [0:7]  w19;
  wire [0:7]  w20;
  wire [0:7]  w21;
  wire [0:7]  w22;
  wire [0:7]  w23;
  wire [0:7]  w24;

  assign v4642b6 = w8;
  assign w9      = vc67cc0;
  assign w12     = v7bf4f3;
  assign vc16efd = w16;

  vcb23aa v8e0bba (
    .v4642b6(w0),
    .v62bf25(w2),
    .v39966a(w21),
    .veb2f59(w24)
  );

  vc3c498 v917bbf (
    .vb9cfc3(w0),
    .veeaa8e(w1),
    .v4642b6(w3),
    .v45c6ee(w20),
    .v20212e(w23)
  );

  v8cc49c v03c3e3 (
    .vb334ae(w1),
    .v2b8a97(w2),
    .v14a530(w4)
  );

  vc3c498 vf0db78 (
    .vb9cfc3(w3),
    .veeaa8e(w5),
    .v4642b6(w6),
    .v45c6ee(w18),
    .v20212e(w22)
  );

  va52e3b v67022b (
    .vbf8961(w4),
    .vf7d213(w5),
    .v6d326e(w7)
  );

  vdf0f3f v2bc38d (
    .ve841af(w9),
    .v6eb35c(w10),
    .vc6471a(w24)
  );

  vab13f0 v750bb9 (
    .vb18564(w10),
    .vf0a06e(w11),
    .v5246f6(w23)
  );

  v306ca3 vb8499e (
    .v91b9c1(w11),
    .vef5eee(w19),
    .vd3ef3b(w22)
  );

  vdf0f3f vec80d3 (
    .ve841af(w12),
    .v6eb35c(w13),
    .vc6471a(w21)
  );

  vab13f0 v0d470e (
    .vb18564(w13),
    .vf0a06e(w14),
    .v5246f6(w20)
  );

  v306ca3 vd19231 (
    .v91b9c1(w14),
    .vef5eee(w17),
    .vd3ef3b(w18)
  );

  vc3c498 v2c17f7 (
    .vb9cfc3(w6),
    .v4642b6(w8),
    .veeaa8e(w15),
    .v45c6ee(w17),
    .v20212e(w19)
  );

  vab06af v6d700b (
    .v7df8bd(w7),
    .vea9d11(w15),
    .v7d0a31(w16)
  );
endmodule

//---------------------------------------------------
//-- Adder-32bits
//---------------------------------------------------
//---- Top entity
module vcb23aa (
  input  [7:0] v39966a,
  input  [7:0] veb2f59,
  output       v4642b6,
  output [7:0] v62bf25
);
  wire [0:7] w0;
  wire [0:7] w1;
  wire [0:3] w2;
  wire [0:3] w3;
  wire [0:7] w4;
  wire       w5;
  wire       w6;
  wire [0:3] w7;
  wire [0:3] w8;
  wire [0:3] w9;
  wire [0:3] w10;

  assign w0      = veb2f59;
  assign w1      = v39966a;
  assign v62bf25 = w4;
  assign v4642b6 = w5;

  v6bdcd9 vd88c66 (
    .vcc8c7c(w0),
    .v651522(w9),
    .v2cc41f(w10)
  );

  v6bdcd9 v26a0bb (
    .vcc8c7c(w1),
    .v651522(w7),
    .v2cc41f(w8)
  );

  v25966b v9ea427 (
    .v817794(w3),
    .v4642b6(w6),
    .v0550b6(w8),
    .v24708e(w10)
  );

  vafb28f vc75346 (
    .v515fe7(w2),
    .v3c88fc(w3),
    .va9ac17(w4)
  );

  va1ce30 v40c17f (
    .v817794(w2),
    .v4642b6(w5),
    .vb9cfc3(w6),
    .v0550b6(w7),
    .v24708e(w9)
  );
endmodule

//---------------------------------------------------
//-- Adder-8bits
//---------------------------------------------------
//---- Top entity
module v6bdcd9 (
  input  [7:0] vcc8c7c,
  output [3:0] v651522,
  output [3:0] v2cc41f
);
  wire [0:3] w0;
  wire [0:3] w1;
  wire [0:7] w2;

  assign v651522 = w0;
  assign v2cc41f = w1;
  assign w2      = vcc8c7c;

  v6bdcd9_v9a2a06 v9a2a06 (
    .o1(w0),
    .o0(w1),
    .i(w2)
  );
endmodule

//---------------------------------------------------
//-- Bus8-Split-half
//---------------------------------------------------
module v6bdcd9_v9a2a06 (
  input  [7:0] i,
  output [3:0] o1,
  output [3:0] o0
);
  assign o1 = i[7:4];
  assign o0 = i[3:0];
endmodule

//---- Top entity
module v25966b (
  input  [3:0] v0550b6,
  input  [3:0] v24708e,
  output       v4642b6,
  output [3:0] v817794
);
  wire        w0;
  wire        w1;
  wire        w2;
  wire        w3;
  wire        w4;
  wire [0:3]  w5;
  wire [0:3]  w6;
  wire [0:3]  w7;
  wire        w8;
  wire        w9;
  wire        w10;
  wire        w11;
  wire        w12;
  wire        w13;
  wire        w14;
  wire        w15;
  wire        w16;
  wire        w17;
  wire        w18;

  assign w5      = v24708e;
  assign w6      = v0550b6;
  assign v817794 = w7;
  assign v4642b6 = w9;

  v1ea21d vdbe125 (
    .v4642b6(w0),
    .v8e8a67(w2),
    .v27dec4(w15),
    .v82de4f(w18)
  );

  vad119b vb8ad86 (
    .v0ef266(w0),
    .v8e8a67(w1),
    .v4642b6(w3),
    .v27dec4(w14),
    .v82de4f(w17)
  );

  vad119b v5d29b2 (
    .v0ef266(w3),
    .v8e8a67(w4),
    .v4642b6(w8),
    .v27dec4(w12),
    .v82de4f(w16)
  );

  vc4f23a vf4a6ff (
    .v985fcb(w5),
    .v4f1fd3(w13),
    .vda577d(w16),
    .v3f8943(w17),
    .v64d863(w18)
  );

  vc4f23a v9d4632 (
    .v985fcb(w6),
    .v4f1fd3(w11),
    .vda577d(w12),
    .v3f8943(w14),
    .v64d863(w15)
  );

  v84f0a1 v140dbf (
    .vee8a83(w1),
    .v03aaf0(w2),
    .vf8041d(w4),
    .v11bca5(w7),
    .vd84a57(w10)
  );

  vad119b v5c5937 (
    .v0ef266(w8),
    .v4642b6(w9),
    .v8e8a67(w10),
    .v27dec4(w11),
    .v82de4f(w13)
  );
endmodule

//---------------------------------------------------
//-- Adder-4bits
//---------------------------------------------------
//---- Top entity
module v1ea21d (
  input  v27dec4,
  input  v82de4f,
  output v4642b6,
  output v8e8a67
);
  wire w0;
  wire w1;
  wire w2;
  wire w3;
  wire w4;

  assign w0      = v82de4f;
  assign w1      = v27dec4;
  assign v4642b6 = w3;
  assign v8e8a67 = w4;

  vad119b vb820a1 (
    .v82de4f(w0),
    .v27dec4(w1),
    .v0ef266(w2),
    .v4642b6(w3),
    .v8e8a67(w4)
  );

  vd30ca9 v23ebb6 (
    .v9fb85f(w2)
  );
endmodule

//---------------------------------------------------
//-- Adder-1bit
//---------------------------------------------------
//---- Top entity
module vad119b (
  input  v27dec4,
  input  v82de4f,
  input  v0ef266,
  output v4642b6,
  output v8e8a67
);
  wire w0;
  wire w1;
  wire w2;
  wire w3;
  wire w4;
  wire w5;
  wire w6;
  wire w7;
  wire w8;
  wire w9;
  wire w10;
  wire w11;

  assign v8e8a67 = w1;
  assign v4642b6 = w5;
  assign w6      = v27dec4;
  assign w7      = v27dec4;
  assign w8      = v82de4f;
  assign w9      = v82de4f;
  assign w10     = v0ef266;
  assign w11     = v0ef266;
  assign w2      = w0;
  assign w7      = w6;
  assign w9      = w8;
  assign w11     = w10;

  vd12401 v2e3d9f (
    .vcbab45(w0),
    .v0e28cb(w7),
    .v3ca442(w9)
  );

  vd12401 vb50462 (
    .v0e28cb(w0),
    .vcbab45(w1),
    .v3ca442(w11)
  );

  vba518e v4882f4 (
    .v3ca442(w2),
    .vcbab45(w3),
    .v0e28cb(w10)
  );

  vba518e v8fcf41 (
    .vcbab45(w4),
    .v0e28cb(w6),
    .v3ca442(w8)
  );

  v873425 vc5b8b9 (
    .v3ca442(w3),
    .v0e28cb(w4),
    .vcbab45(w5)
  );
endmodule

//---------------------------------------------------
//-- AdderC-1bit
//---------------------------------------------------
//---- Top entity
module vd12401 (
  input  v0e28cb,
  input  v3ca442,
  output vcbab45
);
  wire w0;
  wire w1;
  wire w2;

  assign w0      = v0e28cb;
  assign w1      = v3ca442;
  assign vcbab45 = w2;

  vd12401_vf4938a vf4938a (
    .a(w0),
    .b(w1),
    .c(w2)
  );
endmodule

//---------------------------------------------------
//-- XOR2
//---------------------------------------------------
module vd12401_vf4938a (
  input  a,
  input  b,
  output c
);
  assign c = a ^ b;
endmodule

//---- Top entity
module vc4f23a (
  input  [3:0] v985fcb,
  output       v4f1fd3,
  output       vda577d,
  output       v3f8943,
  output       v64d863
);
  wire       w0;
  wire       w1;
  wire       w2;
  wire       w3;
  wire [0:3] w4;

  assign v3f8943 = w0;
  assign v64d863 = w1;
  assign vda577d = w2;
  assign v4f1fd3 = w3;
  assign w4      = v985fcb;

  vc4f23a_v9a2a06 v9a2a06 (
    .o1(w0),
    .o0(w1),
    .o2(w2),
    .o3(w3),
    .i(w4)
  );
endmodule

//---------------------------------------------------
//-- Bus4-Split-all
//---------------------------------------------------
module vc4f23a_v9a2a06 (
  input  [3:0] i,
  output       o3,
  output       o2,
  output       o1,
  output       o0
);
  assign o3 = i[3];
  assign o2 = i[2];
  assign o1 = i[1];
  assign o0 = i[0];
endmodule

//---- Top entity
module v84f0a1 (
  input        vd84a57,
  input        vf8041d,
  input        vee8a83,
  input        v03aaf0,
  output [3:0] v11bca5
);
  wire       w0;
  wire       w1;
  wire       w2;
  wire       w3;
  wire [0:3] w4;

  assign w0      = vee8a83;
  assign w1      = v03aaf0;
  assign w2      = vf8041d;
  assign w3      = vd84a57;
  assign v11bca5 = w4;

  v84f0a1_v9a2a06 v9a2a06 (
    .i1(w0),
    .i0(w1),
    .i2(w2),
    .i3(w3),
    .o(w4)
  );
endmodule

//---------------------------------------------------
//-- Bus4-Join-all
//---------------------------------------------------
module v84f0a1_v9a2a06 (
  input        i3,
  input        i2,
  input        i1,
  input        i0,
  output [3:0] o
);
  assign o = {i3, i2, i1, i0};
endmodule

//---- Top entity
module vafb28f (
  input  [3:0] v515fe7,
  input  [3:0] v3c88fc,
  output [7:0] va9ac17
);
  wire [0:7] w0;
  wire [0:3] w1;
  wire [0:3] w2;

  assign va9ac17 = w0;
  assign w1      = v515fe7;
  assign w2      = v3c88fc;

  vafb28f_v9a2a06 v9a2a06 (
    .o(w0),
    .i1(w1),
    .i0(w2)
  );
endmodule

//---------------------------------------------------
//-- Bus8-Join-half
//---------------------------------------------------
module vafb28f_v9a2a06 (
  input  [3:0] i1,
  input  [3:0] i0,
  output [7:0] o
);
  assign o = {i1, i0};
endmodule

//---- Top entity
module va1ce30 (
  input  [3:0] v0550b6,
  input  [3:0] v24708e,
  input        vb9cfc3,
  output       v4642b6,
  output [3:0] v817794
);
  wire        w0;
  wire        w1;
  wire        w2;
  wire        w3;
  wire        w4;
  wire [0:3]  w5;
  wire [0:3]  w6;
  wire [0:3]  w7;
  wire        w8;
  wire        w9;
  wire        w10;
  wire        w11;
  wire        w12;
  wire        w13;
  wire        w14;
  wire        w15;
  wire        w16;
  wire        w17;
  wire        w18;
  wire        w19;

  assign w5      = v24708e;
  assign w6      = v0550b6;
  assign v817794 = w7;
  assign v4642b6 = w9;
  assign w11     = vb9cfc3;

  vad119b vb8ad86 (
    .v0ef266(w0),
    .v8e8a67(w1),
    .v4642b6(w3),
    .v27dec4(w15),
    .v82de4f(w18)
  );

  vad119b v5d29b2 (
    .v0ef266(w3),
    .v8e8a67(w4),
    .v4642b6(w8),
    .v27dec4(w13),
    .v82de4f(w17)
  );

  vc4f23a vf4a6ff (
    .v985fcb(w5),
    .v4f1fd3(w14),
    .vda577d(w17),
    .v3f8943(w18),
    .v64d863(w19)
  );

  vc4f23a v9d4632 (
    .v985fcb(w6),
    .v4f1fd3(w12),
    .vda577d(w13),
    .v3f8943(w15),
    .v64d863(w16)
  );

  v84f0a1 v140dbf (
    .vee8a83(w1),
    .v03aaf0(w2),
    .vf8041d(w4),
    .v11bca5(w7),
    .vd84a57(w10)
  );

  vad119b v5c5937 (
    .v0ef266(w8),
    .v4642b6(w9),
    .v8e8a67(w10),
    .v27dec4(w12),
    .v82de4f(w14)
  );

  vad119b v3599be (
    .v4642b6(w0),
    .v8e8a67(w2),
    .v0ef266(w11),
    .v27dec4(w16),
    .v82de4f(w19)
  );
endmodule

//---------------------------------------------------
//-- AdderC-4bits
//---------------------------------------------------
//---- Top entity
module vc3c498 (
  input  [7:0] v45c6ee,
  input  [7:0] v20212e,
  input        vb9cfc3,
  output       v4642b6,
  output [7:0] veeaa8e
);
  wire        w0;
  wire        w1;
  wire [0:7]  w2;
  wire [0:7]  w3;
  wire [0:7]  w4;
  wire [0:3]  w5;
  wire [0:3]  w6;
  wire [0:3]  w8;
  wire [0:3]  w9;
  wire [0:3]  w10;
  wire [0:3]  w11;
  wire        w7;

  assign w1      = vb9cfc3;
  assign w2      = v45c6ee;
  assign w3      = v20212e;
  assign veeaa8e = w4;
  assign v4642b6 = w7;

  v6bdcd9 v8d795a (
    .vcc8c7c(w3),
    .v651522(w10),
    .v2cc41f(w11)
  );

  v6bdcd9 v23dbc5 (
    .vcc8c7c(w2),
    .v651522(w8),
    .v2cc41f(w9)
  );

  vafb28f vef3a58 (
    .va9ac17(w4),
    .v3c88fc(w5),
    .v515fe7(w6)
  );

  va1ce30 v0ff71a (
    .v4642b6(w0),
    .vb9cfc3(w1),
    .v817794(w5),
    .v0550b6(w9),
    .v24708e(w11)
  );

  va1ce30 v12f94f (
    .vb9cfc3(w0),
    .v817794(w6),
    .v4642b6(w7),
    .v0550b6(w8),
    .v24708e(w10)
  );
endmodule

//---------------------------------------------------
//-- AdderC-8bits
//---------------------------------------------------
//---- Top entity
module v8cc49c (
  input  [7:0] vb334ae,
  input  [7:0] v2b8a97,
  output [15:0] v14a530
);
  wire [0:15] w0;
  wire [0:7]  w1;
  wire [0:7]  w2;

  assign v14a530 = w0;
  assign w1      = v2b8a97;
  assign w2      = vb334ae;

  v8cc49c_v9a2a06 v9a2a06 (
    .o(w0),
    .i0(w1),
    .i1(w2)
  );
endmodule

//---------------------------------------------------
//-- Bus16-Join-half
//---------------------------------------------------
module v8cc49c_v9a2a06 (
  input  [7:0] i1,
  input  [7:0] i0,
  output [15:0] o
);
  assign o = {i1, i0};
endmodule

//---- Top entity
module va52e3b (
  input  [7:0]  vf7d213,
  input  [15:0] vbf8961,
  output [23:0] v6d326e
);
  wire [0:15] w0;
  wire [0:23] w1;
  wire [0:7]  w2;

  assign w0      = vbf8961;
  assign v6d326e = w1;
  assign w2      = vf7d213;

  va52e3b_v9a2a06 v9a2a06 (
    .i0(w0),
    .o(w1),
    .i1(w2)
  );
endmodule

//---------------------------------------------------
//-- Bus24-Join-8-16
//---------------------------------------------------
module va52e3b_v9a2a06 (
  input  [7:0]  i1,
  input  [15:0] i0,
  output [23:0] o
);
  assign o = {i1, i0};
endmodule

//---- Top entity
module vdf0f3f (
  input  [31:0] ve841af,
  output [23:0] v6eb35c,
  output [7:0]  vc6471a
);
  wire [0:31] w0;
  wire [0:7]  w1;
  wire [0:23] w2;

  assign w0      = ve841af;
  assign vc6471a = w1;
  assign v6eb35c = w2;

  vdf0f3f_v9a2a06 v9a2a06 (
    .i(w0),
    .o0(w1),
    .o1(w2)
  );
endmodule

//---------------------------------------------------
//-- Bus32-Split-8-24
//---------------------------------------------------
module vdf0f3f_v9a2a06 (
  input  [31:0] i,
  output [23:0] o1,
  output [7:0]  o0
);
  assign o1 = i[31:8];
  assign o0 = i[7:0];
endmodule

//---- Top entity
module vab13f0 (
  input  [23:0] vb18564,
  output [15:0] vf0a06e,
  output [7:0]  v5246f6
);
  wire [0:23] w0;
  wire [0:15] w1;
  wire [0:7]  w2;

  assign w0      = vb18564;
  assign vf0a06e = w1;
  assign v5246f6 = w2;

  vab13f0_v9a2a06 v9a2a06 (
    .i(w0),
    .o1(w1),
    .o0(w2)
  );
endmodule

//---------------------------------------------------
//-- Bus24-Split-16-8
//---------------------------------------------------
module vab13f0_v9a2a06 (
  input  [23:0] i,
  output [15:0] o1,
  output [7:0]  o0
);
  assign o1 = i[23:8];
  assign o0 = i[7:0];
endmodule

//---- Top entity
module v306ca3 (
  input  [15:0] v91b9c1,
  output [7:0]  vef5eee,
  output [7:0]  vd3ef3b
);
  wire [0:15] w0;
  wire [0:7]  w1;
  wire [0:7]  w2;

  assign w0      = v91b9c1;
  assign vef5eee = w1;
  assign vd3ef3b = w2;

  v306ca3_v9a2a06 v9a2a06 (
    .i(w0),
    .o1(w1),
    .o0(w2)
  );
endmodule

//---------------------------------------------------
//-- Bus16-Split-half
//---------------------------------------------------
module v306ca3_v9a2a06 (
  input  [15:0] i,
  output [7:0]  o1,
  output [7:0]  o0
);
  assign o1 = i[15:8];
  assign o0 = i[7:0];
endmodule

//---- Top entity
module vab06af (
  input  [7:0]  vea9d11,
  input  [23:0] v7df8bd,
  output [31:0] v7d0a31
);
  wire [0:23] w0;
  wire [0:31] w1;
  wire [0:7]  w2;

  assign w0      = v7df8bd;
  assign v7d0a31 = w1;
  assign w2      = vea9d11;

  vab06af_v9a2a06 v9a2a06 (
    .i0(w0),
    .o(w1),
    .i1(w2)
  );
endmodule

//---------------------------------------------------
//-- Bus32-Join-8-24
//---------------------------------------------------
module vab06af_v9a2a06 (
  input  [7:0]  i1,
  input  [23:0] i0,
  output [31:0] o
);
  assign o = {i1, i0};
endmodule

//---- Top entity
module va63735 (
  input  [31:0] v1069e2,
  input  [31:0] vd448df,
  output        v4642b6
);
  wire [0:31] w0;
  wire [0:31] w1;
  wire        w2;

  assign w0      = v1069e2;
  assign w1      = vd448df;
  assign v4642b6 = w2;

  va63735_v7d150e v7d150e (
    .a(w0),
    .b(w1),
    .ge(w2)
  );
endmodule

//---------------------------------------------------
//-- Geu-32-Bits_v
//---------------------------------------------------
module va63735_v7d150e (
  input  [31:0] a,
  input  [31:0] b,
  output        ge
);
  assign ge = (a >= b);
endmodule

//---- Top entity
module vd5bdd7 #(
  parameter v4800df = 0
) (
  input        v6dda25,
  input        va5013b,
  input  [31:0] v9406e4,
  input        v23125b,
  output       ve74064,
  output       v0c9980,
  output [31:0] v4db459,
  output       v8c0d77
);
  localparam p0 = v4800df;
  wire [0:31] w1;
  wire        w2;
  wire [0:31] w3;
  wire        w4;
  wire        w5;

  assign v4db459 = w1;
  assign w2      = v6dda25;
  assign w3      = v9406e4;
  assign w4      = va5013b;
  assign w5      = v23125b;
 assign ve74064 = 1'b0;
assign v0c9980 = 1'b0;
assign v8c0d77 = 1'b0;

  vd5bdd7_vb9285f #(
    .INI(p0)
  ) vb9285f (
    .q(w1),
    .clk(w2),
    .d(w3),
    .rst(w4),
    .load(w5)
  );
endmodule

//---------------------------------------------------
//-- 32-Reg-rst
//---------------------------------------------------
module vd5bdd7_vb9285f #(
  parameter INI = 0
) (
  input        clk,
  input        rst,
  input  [31:0] d,
  input        load,
  output [31:0] q
);
  localparam N = 32;
  reg [N-1:0] qi = INI;

  always @(posedge clk) begin
    if (rst == 1'b1)
      qi <= INI;
    else if (load == 1'b1)
      qi <= d;
  end

  assign q = qi;
endmodule

//---- Top entity
module vef2764 #(
  parameter v573b2a = 0
) (
  input  v6dda25,
  input  v27dec4,
  input  v92a149,
  output v4642b6
);
  localparam p3 = v573b2a;
  wire       w0;
  wire       w1;
  wire       w2;
  wire       w4;

  assign w0      = v27dec4;
  assign w1      = v92a149;
  assign w2      = v6dda25;
  assign v4642b6 = w4;

  vef2764_v56c60e #(
    .INI(p3)
  ) v56c60e (
    .set(w0),
    .reset(w1),
    .clk(w2),
    .q(w4)
  );
endmodule

//---------------------------------------------------
//-- RS-FF-set-verilog
//---------------------------------------------------
module vef2764_v56c60e #(
  parameter INI = 0
) (
  input  clk,
  input  set,
  input  reset,
  output q
);
  reg qi = INI;

  always @(posedge clk) begin
    if (set == 1'b1)
      qi <= 1'b1;
    else if (reset == 1'b1)
      qi <= 1'b0;
  end

  assign q = qi;
endmodule

//---- Top entity
module v12181a #(
  parameter v001ed5 = 1
) (
  input  vd6bebe,
  output v4642b6
);
  localparam p1 = v001ed5;
  wire       w0;
  wire       w2;
  wire       w3;

  assign v4642b6 = w2;
  assign w3      = vd6bebe;

  vd30ca9 v0ad98b (
    .v9fb85f(w0)
  );

  v58ed2b #(
    .v71e305(p1)
  ) v7d53db (
    .vf54559(w0),
    .ve8318d(w2),
    .va4102a(w3)
  );
endmodule

//---------------------------------------------------
//-- start
//---------------------------------------------------
//---- Top entity
module v58ed2b #(
  parameter v71e305 = 0
) (
  input  va4102a,
  input  vf54559,
  output va58c5b,
  output ve8318d
);
  localparam p2 = v71e305;
  wire       w0;
  wire       w1;
  wire       w3;

  assign w0      = va4102a;
  assign ve8318d = w1;
  assign w3      = vf54559;
    assign va58c5b = 1'b0;

  v58ed2b_vb8adf8 #(
    .INI(p2)
  ) vb8adf8 (
    .clk(w0),
    .q(w1),
    .d(w3)
  );
endmodule

//---------------------------------------------------
//-- sys-DFF-verilog
//---------------------------------------------------
module v58ed2b_vb8adf8 #(
  parameter INI = 0
) (
  input  clk,
  input  d,
  output q
);
  reg qi = INI;

  always @(posedge clk)
    qi <= d;

  assign q = qi;
endmodule

//---- Top entity
module vb7f713 #(
  parameter v8bcde4 = 0
) (
  input  v6dda25,
  input  vb5e8cd,
  output v4642b6
);
  localparam p0 = v8bcde4;
  wire       w1;
  wire       w2;
  wire       w3;

  assign w1      = v6dda25;
  assign w2      = vb5e8cd;
  assign v4642b6 = w3;

  vb7f713_v4a32dd #(
    .INI(p0)
  ) v4a32dd (
    .clk(w1),
    .t(w2),
    .q(w3)
  );
endmodule

//---------------------------------------------------
//-- TFF-verilog
//---------------------------------------------------
module vb7f713_v4a32dd #(
  parameter INI = 0
) (
  input  clk,
  input  t,
  output q
);
  reg qi = INI;

  always @(posedge clk) begin
    if (t == 1'b1)
      qi <= ~qi;
  end

  assign q = qi;
endmodule

module main_v3d4960 (
  input        clock,
  input        disp_sel,
  output [7:0] OUT
);
  reg [7:0] cnt;
  reg [7:0] data_out;

  reg [0:0] var_disp_sel;
  reg [7:0] cnt_high;
  reg [7:0] cnt_low;

  assign OUT = data_out;

  always @(posedge clock) begin
    if (cnt >= 99)
      cnt <= 0;

    if (cnt < 99)
      cnt <= cnt + 1;
  end

  always @(posedge disp_sel) begin
    var_disp_sel <= ~var_disp_sel;
    cnt_high     <= cnt / 10;
    cnt_low      <= cnt % 10;

    if (var_disp_sel == 1) begin
      case (cnt_low)
        0: data_out = 8'b00000010;
        1: data_out = 8'b10011110;
        2: data_out = 8'b00100100;
        3: data_out = 8'b00001100;
        4: data_out = 8'b10011000;
        5: data_out = 8'b01001000;
        6: data_out = 8'b01000000;
        7: data_out = 8'b00011110;
        8: data_out = 8'b00000000;
        9: data_out = 8'b00001000;
        default: data_out = 8'b11111110;
      endcase
    end

    if (var_disp_sel == 0) begin
      case (cnt_high)
        0: data_out = 8'b00000010;
        1: data_out = 8'b10011110;
        2: data_out = 8'b00100100;
        3: data_out = 8'b00001100;
        4: data_out = 8'b10011000;
        5: data_out = 8'b01001000;
        6: data_out = 8'b01000000;
        7: data_out = 8'b00011110;
        8: data_out = 8'b00000000;
        9: data_out = 8'b00001000;
        default: data_out = 8'b11111110;
      endcase
    end

    data_out[0] = var_disp_sel;
  end
endmodule
